import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='px-4'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='mt-4'>
        <h1 className='text-red-300 text-2xl'>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
      </main>

      <footer className='bg-black p-4'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        ></a>
      </footer>
    </div>
  )
}

export default Home
